const scannerSchema = {
	id: true,
	address: true,
	network: true,
	inProgress: true,
	name: true,
	contractName: true,
	firstTxFrom: true,
	firstTxDate: true,
	firstTxBlock: true,
	onChainScanned: true,
	staticAnalizeScanned: true,
	diffCheckScanned: true,
	logo: true,
	compilerVersion: true,
	txCount: true,
	initialFunder: true,
	initialFunding: true,
	outdatedCompiler: true,
	scannedVersion: true,
	scannerVersion: true,
	protocol: true,
	whitelisted: true,
	estimatedAnalyzingTime: true,
	rescanCount: true,
	deploymentBlock: true,
	sourceCodeLink: true,
	link: true,
};

export { scannerSchema };
