const defaultContract = {
	hasVulnerableWithrawlFunction: { result: false, issues: [] },
	hasReeentrancy: { result: false, issues: [] },
	arelocksDetected: { result: false, issues: [] },
	hasVerifiedSourceCode: { result: false, issues: [] },
	isMintable: { result: false, issues: [] },
	isTransferPausable: { result: false, issues: [] },
	canContractBeUpgraded: { result: false, issues: [] },
	hasBlacklist: { result: false, issues: [] },
	hasTransferFee: { result: false, issues: [] },
	canTokenBeSoldThroughAMM: { result: false, issues: [] },
	hasTransferLimit: { result: false, issues: [] },
	hasApprovalVulnerability: { result: false, issues: [] },
	canOwnerAbuseApprovals: { result: false, issues: [] },
	hasInterfaceErrors: { result: false, issues: [] },
	hasBlockingLoops: { result: false, issues: [] },
	hasCentralizedBalanceControls: { result: false, issues: [] },
	hasTransferCooldown: { result: false, issues: [] },
	hasApprovalRestrictions: { result: false, issues: [] },
	hasExternalCalls: { result: false, issues: [] },
	hasAirdropSpecificCode: { result: false, issues: [] },
	hasVulnerableOwnershipFunctions: { result: false, issues: [] },
	canRetrieveOwnership: { result: false, issues: [] },
	isRecentlyDeployedContract: { result: false, issues: [] },
	hasMixers: { result: false, issues: [] },
	canAdjustMaximalSupply: { result: false, issues: [] },
	ownerHasPreviousScams: { result: false, issues: [] },
	canUserTaxBeModified: { result: false, issues: [] },
	canWalletsBeWhitelisted: { result: false, issues: [] },
	canTransfersBeBlockedViaChangingRouter: { result: false, issues: [] },
	hasEthDraining: { result: false, issues: [] },
	hasRecentInteraction: { result: false, issues: [] },
	hasNativeTokenDrainage: { result: false, issues: [] },
	hasHardcodedUniswapRouter: { result: false, issues: [] },
	hasUnusualOnChainMarkers: { result: false, issues: [] },
	hasHighRevocations: { result: false, issues: [] },
	isInitializerProtected: { result: false, issues: [] },
};

export { defaultContract };
